# Copyright 2021 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

FROM alpine:latest

RUN yum update
RUN yum install iproute -y

WORKDIR /app

RUN ip addr add 127.0.0.1/32 dev lo

RUN ip link set dev lo up

COPY server-test ./
COPY run.sh ./

CMD ["./server-test","8","50"]
